import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { UserProvider } from "../context/UserContext";
import { ToastProvider } from "../context/ToastContext";
import ToasterContainer from "../components/ToasterContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <ToastProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
          >
            <div className="flex min-h-screen flex-col">
              <ToasterContainer />
              <Navbar />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </body>
        </ToastProvider>
      </UserProvider>
    </html>
  );
}
